-- ============================================
-- 0. CREATE DATABASE (chỉ chạy được nếu bạn có quyền tạo DB)
-- Nếu trên cloud (Neon, Supabase), thường bạn KHÔNG cần đoạn này
-- ============================================
-- CREATE DATABASE petcarex;
-- \c petcarex;

-- Với hầu hết cloud Postgres, bạn chỉ cần chắc chắn đang kết nối vào DB đúng tên.

-- ============================================
-- 1. MASTER TABLES
-- ============================================

-- 1.1 Branch
CREATE TABLE branch (
    branch_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100)      NOT NULL,
    address     VARCHAR(200)      NOT NULL,
    phone       VARCHAR(20)       NOT NULL UNIQUE,
    open_time   TIME(0)           NOT NULL,
    close_time  TIME(0)           NOT NULL,
    is_active   BOOLEAN           NOT NULL DEFAULT TRUE,
    CONSTRAINT ck_branch_time CHECK (open_time < close_time)
);

-- 1.2 Warehouse
CREATE TABLE warehouse (
    warehouse_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id    INTEGER      NOT NULL REFERENCES branch(branch_id),
    name         VARCHAR(100) NOT NULL,
    phone        VARCHAR(20),
    address      VARCHAR(200) NOT NULL
);

-- 1.3 Service
CREATE TABLE service (
    service_id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_name  VARCHAR(100)     NOT NULL,
    service_type  VARCHAR(30)      NOT NULL,
    base_price    NUMERIC(18,2)    NOT NULL DEFAULT 0,
    description   VARCHAR(500),
    is_active     BOOLEAN          NOT NULL DEFAULT TRUE,
    CONSTRAINT ck_service_type CHECK (service_type IN ('Exam','Vaccination','Other')),
    CONSTRAINT ck_service_price CHECK (base_price >= 0)
);

-- 1.4 Product
CREATE TABLE product (
    product_id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_name  VARCHAR(100)   NOT NULL,
    product_type  VARCHAR(30)    NOT NULL,
    unit          VARCHAR(20)    NOT NULL,
    price         NUMERIC(18,2)  NOT NULL,
    expiry_date   DATE,
    description   VARCHAR(500),
    is_active     BOOLEAN        NOT NULL DEFAULT TRUE,
    CONSTRAINT ck_product_price CHECK (price >= 0)
);

-- 1.5 MembershipTier
CREATE TABLE membership_tier (
    tier_id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tier_name         VARCHAR(50)     NOT NULL UNIQUE,
    qualify_spend_year NUMERIC(18,2)  NOT NULL,
    retain_spend_year  NUMERIC(18,2)  NOT NULL,
    description       VARCHAR(200),
    CONSTRAINT ck_membership_spend CHECK (qualify_spend_year >= 0 AND retain_spend_year >= 0)
);

-- 1.6 Promotion
CREATE TABLE promotion (
    promotion_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    promotion_name VARCHAR(100)    NOT NULL,
    promotion_type VARCHAR(20)     NOT NULL,  -- 'Percent','FixedAmount',...
    value          NUMERIC(18,2)   NOT NULL,
    start_date     DATE            NOT NULL,
    end_date       DATE            NOT NULL,
    conditions     VARCHAR(500),
    is_active      BOOLEAN         NOT NULL DEFAULT TRUE,
    CONSTRAINT ck_promotion_value CHECK (value >= 0),
    CONSTRAINT ck_promotion_date  CHECK (end_date > start_date)
);

-- 1.7 BranchService
CREATE TABLE branch_service (
    branch_id      INTEGER       NOT NULL REFERENCES branch(branch_id),
    service_id     INTEGER       NOT NULL REFERENCES service(service_id),
    price_override NUMERIC(18,2),
    is_available   BOOLEAN       NOT NULL DEFAULT TRUE,
    CONSTRAINT pk_branch_service PRIMARY KEY (branch_id, service_id),
    CONSTRAINT ck_branch_service_price CHECK (price_override IS NULL OR price_override >= 0)
);

-- ============================================
-- 2. CORE ENTITIES: CUSTOMER, PET, EMPLOYEE
-- ============================================

-- 2.1 Customer
CREATE TABLE customer (
    customer_id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name      VARCHAR(100)    NOT NULL,
    gender         CHAR(1),
    date_of_birth  DATE,
    phone          VARCHAR(20)     NOT NULL UNIQUE,
    email          VARCHAR(100)    UNIQUE,
    national_id    VARCHAR(20)     UNIQUE,
    join_date      DATE            NOT NULL DEFAULT CURRENT_DATE,
    total_spending NUMERIC(18,2)   NOT NULL DEFAULT 0,
    tier_id        INTEGER         NOT NULL REFERENCES membership_tier(tier_id),
    loyalty_points INTEGER         NOT NULL DEFAULT 0,
    CONSTRAINT ck_customer_gender CHECK (gender IN ('M','F','O'))
);

-- 2.2 Pet
CREATE TABLE pet (
    pet_id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id   INTEGER       NOT NULL REFERENCES customer(customer_id),
    pet_name      VARCHAR(100)  NOT NULL,
    species       VARCHAR(50)   NOT NULL,
    breed         VARCHAR(100),
    date_of_birth DATE,
    gender        CHAR(1),
    health_status VARCHAR(200),
    CONSTRAINT ck_pet_gender CHECK (gender IN ('M','F','O'))
);

-- 2.3 Employee
CREATE TABLE employee (
    employee_id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id    INTEGER       NOT NULL REFERENCES branch(branch_id),
    full_name    VARCHAR(100)  NOT NULL,
    gender       CHAR(1),
    date_of_birth DATE,
    hire_date    DATE          NOT NULL DEFAULT CURRENT_DATE,
    base_salary  NUMERIC(18,2) DEFAULT 0,
    position     VARCHAR(30)   NOT NULL,
    status       VARCHAR(20)   NOT NULL DEFAULT 'Active',
    CONSTRAINT ck_employee_gender   CHECK (gender IN ('M','F','O')),
    CONSTRAINT ck_employee_position CHECK (position IN ('Doctor','Sales','Receptionist','BranchManager'))
);

-- ============================================
-- 3. INVENTORY & WAREHOUSE TRANSACTIONS
-- ============================================

-- 3.1 Inventory
CREATE TABLE inventory (
    inventory_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quantity     INTEGER        NOT NULL DEFAULT 0,
    update_date  TIMESTAMP(0)   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    warehouse_id INTEGER        NOT NULL REFERENCES warehouse(warehouse_id),
    product_id   INTEGER        NOT NULL REFERENCES product(product_id),
    CONSTRAINT ck_inventory_quantity CHECK (quantity >= 0)
);

-- 3.2 WarehouseTransaction
CREATE TABLE warehouse_transaction (
    transaction_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    warehouse_id     INTEGER       NOT NULL REFERENCES warehouse(warehouse_id),
    product_id       INTEGER       NOT NULL REFERENCES product(product_id),
    transaction_type VARCHAR(10)   NOT NULL,
    quantity         INTEGER       NOT NULL,
    transaction_date TIMESTAMP(0)  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    note             VARCHAR(500),
    CONSTRAINT ck_warehouse_transaction_type CHECK (transaction_type IN ('IMPORT','EXPORT')),
    CONSTRAINT ck_warehouse_transaction_qty  CHECK (quantity > 0)
);

-- ============================================
-- 4. VACCINATION PACKAGES & HISTORY
-- ============================================

-- 4.1 VaccinationPackage
CREATE TABLE vaccination_package (
    package_id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    package_name    VARCHAR(100)   NOT NULL,
    duration_months INTEGER        NOT NULL,
    discount_rate   NUMERIC(5,2)   NOT NULL,
    description     VARCHAR(500),
    is_active       BOOLEAN        NOT NULL DEFAULT TRUE,
    CONSTRAINT ck_vaccination_package_duration CHECK (duration_months > 0),
    CONSTRAINT ck_vaccination_package_discount CHECK (discount_rate >= 0 AND discount_rate <= 100)
);

-- 4.2 VaccinePackageDetail
CREATE TABLE vaccine_package_detail (
    package_id    INTEGER      NOT NULL REFERENCES vaccination_package(package_id),
    service_id    INTEGER      NOT NULL REFERENCES service(service_id),
    required_dose INTEGER      NOT NULL,
    interval_days INTEGER      NOT NULL,
    CONSTRAINT pk_vaccine_package_detail PRIMARY KEY (package_id, service_id),
    CONSTRAINT ck_vaccine_package_detail_required_dose CHECK (required_dose > 0),
    CONSTRAINT ck_vaccine_package_detail_interval_days CHECK (interval_days >= 0)
);

-- 4.3 PetVaccinationPackage
CREATE TABLE pet_vaccination_package (
    pet_package_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pet_id         INTEGER      NOT NULL REFERENCES pet(pet_id),
    package_id     INTEGER      NOT NULL REFERENCES vaccination_package(package_id),
    start_date     DATE         NOT NULL,
    end_date       DATE,
    status         VARCHAR(20)  NOT NULL  -- 'Active','Completed','Cancelled'
);

-- 4.4 VaccinationHistory
CREATE TABLE vaccination_history (
    vaccination_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pet_id         INTEGER      NOT NULL REFERENCES pet(pet_id),
    service_id     INTEGER      NOT NULL REFERENCES service(service_id),
    injection_date TIMESTAMP(0) NOT NULL,
    next_due_date  TIMESTAMP(0),
    notes          VARCHAR(500)
);

-- ============================================
-- 5. BILLING: INVOICE, DETAIL, PAYMENT, FEEDBACK
-- ============================================

-- 5.1 Invoice
CREATE TABLE invoice (
    invoice_id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id       INTEGER       NOT NULL REFERENCES branch(branch_id),
    customer_id     INTEGER       NOT NULL REFERENCES customer(customer_id),
    employee_id     INTEGER       NOT NULL REFERENCES employee(employee_id),
    created_at      TIMESTAMP(0)  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    total_amount    NUMERIC(18,2) NOT NULL DEFAULT 0,
    discount_amount NUMERIC(18,2) NOT NULL DEFAULT 0,
    final_amount    NUMERIC(18,2) NOT NULL DEFAULT 0,
    promotion_id    INTEGER       REFERENCES promotion(promotion_id),
    payment_status  VARCHAR(20)   NOT NULL,
    CONSTRAINT ck_invoice_amount CHECK (total_amount >= 0 AND discount_amount >= 0 AND final_amount >= 0)
);

-- 5.2 InvoiceDetail
CREATE TABLE invoice_detail (
    invoice_id INTEGER       NOT NULL REFERENCES invoice(invoice_id),
    line_no    INTEGER       NOT NULL,
    item_type  VARCHAR(20)   NOT NULL,  -- 'Service' hoặc 'Product'
    service_id INTEGER,
    product_id INTEGER,
    quantity   INTEGER       NOT NULL,
    unit_price NUMERIC(18,2) NOT NULL,
    line_total NUMERIC(18,2) NOT NULL,
    CONSTRAINT pk_invoice_detail PRIMARY KEY (invoice_id, line_no),
    CONSTRAINT fk_invoice_detail_service FOREIGN KEY (service_id) REFERENCES service(service_id),
    CONSTRAINT fk_invoice_detail_product FOREIGN KEY (product_id) REFERENCES product(product_id),
    CONSTRAINT ck_invoice_detail_quantity CHECK (quantity > 0),
    CONSTRAINT ck_invoice_detail_price    CHECK (unit_price >= 0 AND line_total >= 0),
    CONSTRAINT ck_invoice_detail_item_type CHECK (item_type IN ('Service','Product'))
);

-- 5.3 Payment
CREATE TABLE payment (
    payment_id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id     INTEGER       NOT NULL REFERENCES invoice(invoice_id),
    paid_amount    NUMERIC(18,2) NOT NULL,
    payment_method VARCHAR(20)   NOT NULL,
    paid_at        TIMESTAMP(0)  NOT NULL,
    status         VARCHAR(20)   NOT NULL,
    CONSTRAINT ck_payment_amount CHECK (paid_amount >= 0)
);

-- 5.4 Feedback
CREATE TABLE feedback (
    feedback_id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id     INTEGER      NOT NULL REFERENCES invoice(invoice_id),
    employee_id    INTEGER      REFERENCES employee(employee_id),
    service_id     INTEGER      NOT NULL REFERENCES service(service_id),
    service_rating SMALLINT     NOT NULL,
    staff_rating   SMALLINT,
    comment        VARCHAR(1000),
    created_at     TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_feedback_service_rating CHECK (service_rating BETWEEN 1 AND 5),
    CONSTRAINT ck_feedback_staff_rating   CHECK (staff_rating BETWEEN 1 AND 5)
);

-- ============================================
-- 6. MEDICAL RECORDS & PRESCRIPTIONS
-- ============================================

-- 6.1 MedicalRecord
CREATE TABLE medical_record (
    medical_record_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pet_id            INTEGER      NOT NULL REFERENCES pet(pet_id),
    invoice_id        INTEGER      REFERENCES invoice(invoice_id),
    exam_date         TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    diagnosis         VARCHAR(500),
    notes             VARCHAR(500)
);

-- 6.2 MedicalRecordEmployee
CREATE TABLE medical_record_employee (
    medical_record_id INTEGER     NOT NULL REFERENCES medical_record(medical_record_id),
    employee_id       INTEGER     NOT NULL REFERENCES employee(employee_id),
    role_in_exam      VARCHAR(30) NOT NULL,
    CONSTRAINT pk_medical_record_employee PRIMARY KEY (medical_record_id, employee_id)
);

-- 6.3 Prescription
CREATE TABLE prescription (
    prescription_id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    medical_record_id INTEGER     NOT NULL REFERENCES medical_record(medical_record_id),
    created_at       TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    notes            VARCHAR(500)
);

-- 6.4 PrescriptionDetail
CREATE TABLE prescription_detail (
    prescription_id   INTEGER      NOT NULL REFERENCES prescription(prescription_id),
    product_id        INTEGER      NOT NULL REFERENCES product(product_id),
    quantity          INTEGER      NOT NULL,
    unit              VARCHAR(20)  NOT NULL,
    usage_instruction VARCHAR(500),
    CONSTRAINT pk_prescription_detail PRIMARY KEY (prescription_id, product_id),
    CONSTRAINT ck_prescription_detail_quantity CHECK (quantity > 0)
);

-- ============================================
-- 7. APPOINTMENT & REMINDERS
-- ============================================

-- 7.1 Appointment
CREATE TABLE appointment (
    appointment_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id      INTEGER      NOT NULL REFERENCES customer(customer_id),
    pet_id           INTEGER      NOT NULL REFERENCES pet(pet_id),
    branch_id        INTEGER      NOT NULL REFERENCES branch(branch_id),
    employee_id      INTEGER      NOT NULL REFERENCES employee(employee_id),
    appointment_time TIMESTAMP(0) NOT NULL,
    status           VARCHAR(20)  NOT NULL,   -- 'Pending','Confirmed','Completed','Cancelled'
    channel          VARCHAR(20)  NOT NULL    -- 'Online','Offline'
);

-- 7.2 AppointmentService
CREATE TABLE appointment_service (
    appointment_id INTEGER NOT NULL REFERENCES appointment(appointment_id),
    service_id     INTEGER NOT NULL REFERENCES service(service_id),
    CONSTRAINT pk_appointment_service PRIMARY KEY (appointment_id, service_id)
);

-- 7.3 Reminder
CREATE TABLE reminder (
    reminder_id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    appointment_id INTEGER      NOT NULL REFERENCES appointment(appointment_id),
    pet_id         INTEGER      NOT NULL REFERENCES pet(pet_id),
    send_time      TIMESTAMP(0) NOT NULL,
    message        VARCHAR(500) NOT NULL,
    status         VARCHAR(20)  NOT NULL     -- 'Pending','Sent','Failed'
);

-- ============================================
-- 8. EMPLOYEE ASSIGNMENT & TRANSFER
-- ============================================

-- 8.1 EmployeeRoleBranch
CREATE TABLE employee_role_branch (
    employee_id INTEGER     NOT NULL REFERENCES employee(employee_id),
    branch_id   INTEGER     NOT NULL REFERENCES branch(branch_id),
    role_name   VARCHAR(30) NOT NULL,
    CONSTRAINT pk_employee_role_branch PRIMARY KEY (employee_id, branch_id, role_name)
);

-- 8.2 TransferHistory
CREATE TABLE transfer_history (
    transfer_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id INTEGER     NOT NULL REFERENCES employee(employee_id),
    branch_id   INTEGER     NOT NULL REFERENCES branch(branch_id),
    work_date   DATE        NOT NULL,
    shift       VARCHAR(20) NOT NULL,
    note        VARCHAR(200)
);

-- ============================================
-- 9. INDEXES (PostgreSQL)
-- ============================================

-- 9.1 Appointment - tra cứu theo chi nhánh + thời gian + trạng thái
CREATE INDEX ix_appointment_branch_time_status
ON appointment (branch_id, appointment_time, status)
INCLUDE (customer_id, pet_id, employee_id);

-- 9.2 Invoice - thống kê doanh thu theo chi nhánh + thời gian
CREATE INDEX ix_invoice_branch_created_at
ON invoice (branch_id, created_at)
INCLUDE (final_amount, customer_id, promotion_id);

-- 9.3 InvoiceDetail - thống kê dịch vụ/sản phẩm bán chạy
CREATE INDEX ix_invoice_detail_service
ON invoice_detail (service_id)
INCLUDE (invoice_id, quantity, line_total);

CREATE INDEX ix_invoice_detail_product
ON invoice_detail (product_id)
INCLUDE (invoice_id, quantity, line_total);

-- 9.4 VaccinationHistory - tra lịch sử tiêm cho thú cưng
CREATE INDEX ix_vaccination_history_pet_injection_date
ON vaccination_history (pet_id, injection_date)
INCLUDE (service_id, next_due_date);

-- 9.5 Customer - tìm kiếm theo SĐT / Email
CREATE INDEX ix_customer_phone
ON customer (phone);

CREATE INDEX ix_customer_email
ON customer (email);

-- 9.6 Inventory / WarehouseTransaction (optional nhưng useful)
CREATE INDEX ix_inventory_warehouse_product
ON inventory (warehouse_id, product_id);

CREATE INDEX ix_warehouse_transaction_product_date
ON warehouse_transaction (product_id, transaction_date);
